import 'package:flutter/material.dart';

const kMainColor = Color(0xFF75D2DE);
const kSecondaryColor = Color(0xFF4DBACA);
const kThiredColor = Color(0xFFFFFFFF);
const kProductName = 'productName';
const kProductPrice = 'productInterest';
const kProductDescription = 'productDescription';
const kProductDuration = 'productDuration';
const kProductPhone = 'productPhone';
const kProductLatitude = 'productLatitude';
const kProductLongitude = 'productLongitude';
const kProductImage = 'productImage';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';
const kUnActiveColor = Color(0xFFC1BDB8);
const kJackets = 'jackets';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kProductQuantity = 'Quantity';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
